In [3]:
import xarray as xr
import numpy as np

In [40]:
da = xr.DataArray(np.arange(48).reshape(3,4,4), 
                  coords=[np.arange(0,3), np.arange(0,4), np.arange(0,4)],
                  dims=['time','x','y'])

In [41]:
da

<xarray.DataArray (time: 3, x: 4, y: 4)>
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])
Coordinates:
  * time     (time) int32 0 1 2
  * x        (x) int32 0 1 2 3
  * y        (y) int32 0 1 2 3

In [39]:
mask = xr.DataArray([[0,0,0,0],
                     [0,1,1,0],
                     [0,1,1,0],
                     [0,0,0,0]], 
                    coords=[np.arange(0,4), np.arange(0,4)], 
                    dims=['x','y']) #.expand_dims('time', axis=0)
mask

<xarray.DataArray (x: 4, y: 4)>
array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])
Coordinates:
  * x        (x) int32 0 1 2 3
  * y        (y) int32 0 1 2 3

In [43]:
da.where(mask)

<xarray.DataArray (time: 3, x: 4, y: 4)>
array([[[nan, nan, nan, nan],
        [nan,  5.,  6., nan],
        [nan,  9., 10., nan],
        [nan, nan, nan, nan]],

       [[nan, nan, nan, nan],
        [nan, 21., 22., nan],
        [nan, 25., 26., nan],
        [nan, nan, nan, nan]],

       [[nan, nan, nan, nan],
        [nan, 37., 38., nan],
        [nan, 41., 42., nan],
        [nan, nan, nan, nan]]])
Coordinates:
  * time     (time) int32 0 1 2
  * x        (x) int32 0 1 2 3
  * y        (y) int32 0 1 2 3