# Examples of `xarray` resample and groupby
This notebook demonstrates how to use resample and groupby methods to calculate a time series of monthly means and a monthly climatology from daily data.

I'm using an example `DataArray` with dimensions `(time=730, points=10)` as a starting point.  This mimics the type of `DataArray` you would get after extracting 10 points from a grid.

In [1]:
import numpy as np
import xarray as xr
import pandas as pd

### Generate example `DataArray`

In [3]:
time = pd.date_range('2019-01-01', '2020-12-31', freq='D')  # Use pandas to generate time coordinate
ntime = len(time)
npoint = 10
point = np.arange(npoint)

data = np.random.rand(ntime, npoint)  # Use random array as an example

da = xr.DataArray(data, coords=[time, point], dims=['time', 'point'])
da

<xarray.DataArray (time: 731, point: 10)>
array([[0.65701873, 0.1056248 , 0.66238729, ..., 0.57862012, 0.39134141,
        0.51056088],
       [0.44280154, 0.01597275, 0.88643616, ..., 0.31835724, 0.66282825,
        0.41211341],
       [0.03960433, 0.95846886, 0.77140854, ..., 0.81740315, 0.01320619,
        0.16725991],
       ...,
       [0.8886105 , 0.51529869, 0.36500946, ..., 0.47871039, 0.75398455,
        0.27667639],
       [0.43801515, 0.53408605, 0.68797823, ..., 0.24629923, 0.0094385 ,
        0.06276786],
       [0.62998567, 0.95457429, 0.33544239, ..., 0.71033602, 0.87406551,
        0.80446102]])
Coordinates:
  * time     (time) datetime64[ns] 2019-01-01 2019-01-02 ... 2020-12-31
  * point    (point) int64 0 1 2 3 4 5 6 7 8 9

## Resample data to monthly means along time dimension
We want to resample along the `time` dimension at monthly (`M`) frequency and calculate a mean.  If you want variance or standard deviation you can use `var` or `std`

In [20]:
da_mon = da.resample(time='M').mean()
da_mon

<xarray.DataArray (time: 24, point: 10)>
array([[0.42146798, 0.48682141, 0.56932741, 0.62440657, 0.47574911,
        0.48354539, 0.49960549, 0.55148258, 0.48543775, 0.44414693],
       [0.48470503, 0.46655422, 0.58440019, 0.52449895, 0.45923516,
        0.56129195, 0.45254652, 0.44975606, 0.4796995 , 0.48168304],
       [0.47887756, 0.46115276, 0.55638865, 0.5411862 , 0.45666065,
        0.48758625, 0.43937699, 0.47693129, 0.59039733, 0.57859974],
       [0.54063122, 0.52197081, 0.55539021, 0.52940836, 0.53396478,
        0.57810321, 0.49565119, 0.44514735, 0.52962116, 0.52698529],
       [0.52404744, 0.45321872, 0.48937596, 0.54097105, 0.50284593,
        0.48853553, 0.53092215, 0.46223883, 0.52584987, 0.54274324],
       [0.53977113, 0.575859  , 0.52337985, 0.4935902 , 0.50861725,
        0.55096178, 0.44550848, 0.48890202, 0.5667588 , 0.44938471],
       [0.49089945, 0.56918366, 0.50991476, 0.55622165, 0.48918297,
        0.4905745 , 0.52335468, 0.57756368, 0.52958877, 0.41467776],
       [0.55585351, 0.49696798, 0.4520841 , 0.47616968, 0.5051624 ,
        0.56521058, 0.54554302, 0.43047187, 0.53723883, 0.49907465],
       [0.45494455, 0.53685533, 0.41806856, 0.43564686, 0.48081497,
        0.54021414, 0.55137437, 0.43908878, 0.51410765, 0.45684737],
       [0.53519761, 0.43428004, 0.53949681, 0.50393201, 0.55108054,
        0.57304519, 0.53684257, 0.53490188, 0.47261267, 0.50916406],
       [0.58007146, 0.51775332, 0.58427873, 0.45668262, 0.55063947,
        0.54309019, 0.47832268, 0.56738968, 0.41725778, 0.50705325],
       [0.45714931, 0.37327332, 0.47328612, 0.46330168, 0.4610565 ,
        0.5517164 , 0.50952901, 0.48276717, 0.46867465, 0.44159482],
       [0.56483569, 0.45076419, 0.45342608, 0.50399761, 0.5183082 ,
        0.45984797, 0.53881768, 0.53462559, 0.50321235, 0.49246899],
       [0.58455036, 0.47178539, 0.5603917 , 0.47899489, 0.58284477,
        0.5125431 , 0.46464511, 0.53614309, 0.5232385 , 0.48652603],
       [0.48732695, 0.4936653 , 0.57835844, 0.50732711, 0.48169962,
        0.44525814, 0.50029146, 0.4854109 , 0.5589865 , 0.51065816],
       [0.43180142, 0.53089076, 0.58474555, 0.52895542, 0.44990477,
        0.57518985, 0.49868314, 0.53340207, 0.55475325, 0.58404485],
       [0.52115805, 0.46921861, 0.50222851, 0.58985958, 0.57337835,
        0.41960993, 0.52237159, 0.49930321, 0.54025023, 0.54216513],
       [0.43537222, 0.51852122, 0.45192675, 0.51365963, 0.50035083,
        0.52681416, 0.51401151, 0.45987633, 0.51600728, 0.52522138],
       [0.46779553, 0.53846829, 0.53352471, 0.4877724 , 0.42942414,
        0.47578035, 0.38251212, 0.6103667 , 0.5107713 , 0.43669844],
       [0.45792808, 0.58734258, 0.55438414, 0.45126471, 0.45764302,
        0.47343273, 0.48826983, 0.43820899, 0.40511363, 0.53305849],
       [0.55572043, 0.49283029, 0.39651896, 0.41848179, 0.44852523,
        0.60131044, 0.49756726, 0.45196801, 0.64482599, 0.4381898 ],
       [0.5157845 , 0.49543128, 0.50008061, 0.47234153, 0.44276044,
        0.50293005, 0.51234494, 0.58202461, 0.49741371, 0.63254356],
       [0.54614446, 0.58265667, 0.51335523, 0.50283846, 0.61627127,
        0.53808844, 0.43839646, 0.50092161, 0.43579169, 0.559865  ],
       [0.50207277, 0.47437067, 0.49333707, 0.57555024, 0.51884725,
        0.5614917 , 0.48561943, 0.56340257, 0.53267392, 0.43675935]])
Coordinates:
  * time     (time) datetime64[ns] 2019-01-31 2019-02-28 ... 2020-12-31
  * point    (point) int64 0 1 2 3 4 5 6 7 8 9

## Calculate monthly climatology
There is two ways to do this.  First, calculate an average using all days in the time series that fall in a month.  Second, calculate a monthly climatology using monthly values.

In both methods, we use `groupby` to 'group' data based on the month and then calculate a mean.  We can use the `time` coordinate to do this.  We can extract the month number using `da.time.dt.month`

In [24]:
da.time.dt.month

<xarray.DataArray 'month' (time: 731)>
array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])
Coordinates:
  * time     (time) datetime64[ns] 2019-01-01 2019-01-02 ... 2020-12-31

Similarly, `da.time.dt.day`, `da.time.dt.year`, and `da.time.dt.season` can be used to access the day, year and season of each time stamp.  

First method...

In [23]:
da_clim = da.groupby(da.time.dt.month).mean(dim='time')
da_clim

<xarray.DataArray (month: 12, point: 10)>
array([[0.49315183, 0.4687928 , 0.51137674, 0.56420209, 0.49702866,
        0.47169668, 0.51921159, 0.54305408, 0.49432505, 0.46830796],
       [0.53550353, 0.46921569, 0.57218534, 0.50134776, 0.52212426,
        0.5364899 , 0.45870194, 0.49370736, 0.50185092, 0.48414702],
       [0.48310226, 0.47740903, 0.56737354, 0.52425665, 0.46918013,
        0.46642219, 0.46983423, 0.48117109, 0.57469192, 0.54462895],
       [0.48621632, 0.52643078, 0.57006788, 0.52918189, 0.49193477,
        0.57664653, 0.49716717, 0.48927471, 0.5421872 , 0.55551507],
       [0.52260274, 0.46121867, 0.49580223, 0.56541531, 0.53811214,
        0.45407273, 0.52664687, 0.48077102, 0.53305005, 0.54245419],
       [0.48757168, 0.54719011, 0.4876533 , 0.50362491, 0.50448404,
        0.53888797, 0.47975999, 0.47438918, 0.54138304, 0.48730305],
       [0.47934749, 0.55382597, 0.52171974, 0.52199703, 0.45930356,
        0.48317743, 0.4529334 , 0.59396519, 0.52018004, 0.4256881 ],
       [0.5068908 , 0.54215528, 0.50323412, 0.46371719, 0.48140271,
        0.51932166, 0.51690642, 0.43434043, 0.47117623, 0.51606657],
       [0.50533249, 0.51484281, 0.40729376, 0.42706432, 0.4646701 ,
        0.57076229, 0.52447081, 0.4455284 , 0.57946682, 0.44751858],
       [0.52549106, 0.46485566, 0.51978871, 0.48813677, 0.49692049,
        0.53798762, 0.52459376, 0.55846324, 0.48501319, 0.57085381],
       [0.56310796, 0.550205  , 0.54881698, 0.47976054, 0.58345537,
        0.54058932, 0.45835957, 0.53415565, 0.42652474, 0.53345913],
       [0.47961104, 0.42382199, 0.4833116 , 0.51942596, 0.48995188,
        0.55660405, 0.49757422, 0.52308487, 0.50067429, 0.43917708]])
Coordinates:
  * point    (point) int64 0 1 2 3 4 5 6 7 8 9
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12

Second method...

In [27]:
da_clim = da_mon.groupby(da_mon.time.dt.month).mean(dim='time')
da_clim

<xarray.DataArray (month: 12, point: 10)>
array([[0.49315183, 0.4687928 , 0.51137674, 0.56420209, 0.49702866,
        0.47169668, 0.51921159, 0.54305408, 0.49432505, 0.46830796],
       [0.53462769, 0.46916981, 0.57239594, 0.50174692, 0.52103997,
        0.53691753, 0.45859581, 0.49294957, 0.501469  , 0.48410454],
       [0.48310226, 0.47740903, 0.56737354, 0.52425665, 0.46918013,
        0.46642219, 0.46983423, 0.48117109, 0.57469192, 0.54462895],
       [0.48621632, 0.52643078, 0.57006788, 0.52918189, 0.49193477,
        0.57664653, 0.49716717, 0.48927471, 0.5421872 , 0.55551507],
       [0.52260274, 0.46121867, 0.49580223, 0.56541531, 0.53811214,
        0.45407273, 0.52664687, 0.48077102, 0.53305005, 0.54245419],
       [0.48757168, 0.54719011, 0.4876533 , 0.50362491, 0.50448404,
        0.53888797, 0.47975999, 0.47438918, 0.54138304, 0.48730305],
       [0.47934749, 0.55382597, 0.52171974, 0.52199703, 0.45930356,
        0.48317743, 0.4529334 , 0.59396519, 0.52018004, 0.4256881 ],
       [0.5068908 , 0.54215528, 0.50323412, 0.46371719, 0.48140271,
        0.51932166, 0.51690642, 0.43434043, 0.47117623, 0.51606657],
       [0.50533249, 0.51484281, 0.40729376, 0.42706432, 0.4646701 ,
        0.57076229, 0.52447081, 0.4455284 , 0.57946682, 0.44751858],
       [0.52549106, 0.46485566, 0.51978871, 0.48813677, 0.49692049,
        0.53798762, 0.52459376, 0.55846324, 0.48501319, 0.57085381],
       [0.56310796, 0.550205  , 0.54881698, 0.47976054, 0.58345537,
        0.54058932, 0.45835957, 0.53415565, 0.42652474, 0.53345913],
       [0.47961104, 0.42382199, 0.4833116 , 0.51942596, 0.48995188,
        0.55660405, 0.49757422, 0.52308487, 0.50067429, 0.43917708]])
Coordinates:
  * point    (point) int64 0 1 2 3 4 5 6 7 8 9
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12